# Generated by Django 5.2.1 on 2025-12-13 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='PlacePublishing',
        ),
        migrations.RenameField(
            model_name='placepublishing',
            old_name='name',
            new_name='place_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='country',
        ),
        migrations.AddField(
            model_name='book',
            name='place_publishing',
            field=models.ForeignKey(db_column='place_publishing_id', on_delete=django.db.models.deletion.PROTECT, to='books.placepublishing'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='placepublishing',
            table='place_publishing',
        ),
    ]
