# Generated by Django 5.2.9 on 2025-12-19 18:37

from django.db import migrations

NEW_SQL = """
CREATE OR REPLACE FUNCTION add_book(
    p_user_id INTEGER,
    p_book_name VARCHAR(80),
    p_book_year VARCHAR(4),
    p_place_name VARCHAR(80),
    p_author_last_name VARCHAR(80),
    p_author_first_name VARCHAR(80),
    p_author_middle_name VARCHAR(80) DEFAULT ''
) 
RETURNS INTEGER AS $$
DECLARE
    v_place_id INTEGER;
    v_book_id INTEGER;
    v_author_id INTEGER;
BEGIN
    SELECT id INTO v_place_id 
    FROM place_publishing 
    WHERE place_name = p_place_name;
    
    IF v_place_id IS NULL THEN
        INSERT INTO place_publishing (place_name)
        VALUES (p_place_name)
        RETURNING id INTO v_place_id;
    END IF;

    INSERT INTO books (name, year, place_publishing_id)
    VALUES (p_book_name, p_book_year, v_place_id)
    RETURNING id INTO v_book_id;

    SELECT id INTO v_author_id 
    FROM authors 
    WHERE last_name = p_author_last_name 
      AND first_name = p_author_first_name 
      AND middle_name = COALESCE(NULLIF(p_author_middle_name, ''), '');
    
    IF v_author_id IS NULL THEN
        INSERT INTO authors (last_name, first_name, middle_name)
        VALUES (p_author_last_name, p_author_first_name, 
                COALESCE(NULLIF(p_author_middle_name, ''), ''))
        RETURNING id INTO v_author_id;
    END IF;
    
    INSERT INTO user_books (user_id, book_id)
    VALUES (p_user_id, v_book_id);
    
    INSERT INTO book_authors (book_id, author_id)
    VALUES (v_book_id, v_author_id);
    
    RETURN v_book_id;
    
EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION 'Книга уже существует в вашей коллекции';
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Ошибка при добавлении книги: %', SQLERRM;
        RETURN -1;
END;
$$ LANGUAGE plpgsql;
"""

OLD_SQL = """
create or replace function add_book(
    p_user_id integer,
    p_book_name varchar(80),
    p_book_year varchar(4),
    p_place_name varchar(80),
    p_author_last_name varchar(80),
    p_author_first_name varchar(80),
    p_author_middle_name varchar(80) default ''
)

returns integer
as $$
declare
    v_place_id integer;
    v_book_id integer;
    v_author_id integer;
begin
    --Находим или создаем место издания
    insert into place_publishing (place_name) values (p_place_name)
    on conflict (place_name) do nothing
    returning id into v_place_id;

    if v_place_id is null then
        select id into v_place_id
        from place_publishing
        where place_name = p_place_name;
    end if;


    --Создание книгу
    insert into books (name, year, place_publishing_id)
    values (p_book_name, p_book_year, v_place_id)
    returning id into v_book_id;

    
    --Находим или создаем автора
    insert into authors (last_name, first_name, middle_name)
    values (p_author_last_name, p_author_first_name, coalesce(nullif(p_author_middle_name, ''), ''))
    on conflict (last_name, first_name, middle_name) do nothing
    returning id into v_author_id;

    if v_author_id is null then
        select id into v_author_id
        from authors
        where last_name = p_author_last_name
        and first_name = p_author_first_name
        and middle_name = coalesce(nullif(p_author_middle_name, ''), '');
    end if;


    --Создание связи пользователь-книга
    insert into user_books (user_id, book_id)
    values (p_user_id, v_book_id)
    on conflict (user_id, book_id) do nothing;


    --Создание связи книга-автор
    insert into book_authors (book_id, author_id)
    values (v_book_id, v_author_id)
    on conflict (book_id, author_id) do nothing;

    return v_book_id;
exception
    when others then
        raise exception 'Ошибка при добавлении книги: %', sqlerrm;
        return -1;
end;
$$ language plpgsql;
"""

class Migration(migrations.Migration):
    dependencies = [
        ('books', '0002_create_add_book_function'),
    ]
    
    operations = [
        migrations.RunSQL(NEW_SQL, OLD_SQL),
    ]