# Generated by Django 5.2.9 on 2025-12-20 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_create_delete_user_books_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='place_publishing',
            field=models.ForeignKey(db_column='place_publishing_id', on_delete=django.db.models.deletion.PROTECT, to='books.placepublishing'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'year', 'place_publishing')},
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
