# Generated by Django 5.2.9 on 2025-12-20 10:21

from django.db import migrations
import os

def load_sql_from_file(filename):
    sql_path = os.path.join(os.path.dirname(__file__), '..', 'sql', filename)
    with open(sql_path, 'r', encoding='utf-8') as f:
        return f.read()

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_place_publishing_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_from_file('add_book_function.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS add_book;'
        ),
    ]