# Generated by Django 5.2.9 on 2025-12-23 10:54

from django.db import migrations
import os

def load_sql_from_file(filename):
    sql_path = os.path.join(os.path.dirname(__file__), '..', 'sql', filename)
    with open(sql_path, 'r', encoding='utf-8') as f:
        return f.read()

class Migration(migrations.Migration):
    dependencies = [
        ('books', '0010_create_search_books_function')
    ]
    
    operations = [
        migrations.RunSQL(
            sql=load_sql_from_file('add_book_function.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS add_book;'
        ),
        migrations.RunSQL(
            sql=load_sql_from_file('delete_user_books_function.sql'),
            reverse_sql='DROP TABLE IF EXISTS delete_user_books;'
        )
    ]