# Generated by Django 5.2.9 on 2025-12-23 16:40

from django.db import migrations
import os

def load_sql_from_file(filename):
    sql_path = os.path.join(os.path.dirname(__file__), '..', 'sql', filename)
    with open(sql_path, 'r', encoding='utf-8') as f:
        return f.read()

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_create_2_functions_to_do_add_many_authors'),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_from_file('add_book_with_multiple_authors_function.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS add_book_with_multiple_authors;'
        )
    ]