# Generated by Django 5.2.9 on 2025-12-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('login', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
