# Generated by Django 5.2.9 on 2025-12-21 11:52

from django.db import migrations
import os

def load_sql_from_file(filename):
    sql_path = os.path.join(os.path.dirname(__file__), '..', 'sql', filename)
    with open(sql_path, 'r', encoding='utf-8') as f:
        return f.read()

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_update_get_notes_function'),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_from_file('delete_notes_function.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS delete_user_notes;'
        ),
    ]