# Generated by Django 5.2.9 on 2025-12-21 12:15

from django.db import migrations
import os

def load_sql_from_file(filename):
    sql_path = os.path.join(os.path.dirname(__file__), '..', 'sql', filename)
    with open(sql_path, 'r', encoding='utf-8') as f:
        return f.read()

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_create_delete_notes_function'),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_from_file('update_note_function.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS update_user_note;'
        ),
    ]