# Generated by Django 5.2.9 on 2025-12-23 10:50

from django.db import migrations
import os

def load_sql_from_file(filename):
    sql_path = os.path.join(os.path.dirname(__file__), '..', 'sql', filename)
    with open(sql_path, 'r', encoding='utf-8') as f:
        return f.read()

class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0001_initial')
    ]
    
    operations = [
        migrations.RunSQL(
            sql=load_sql_from_file('audit_log_table.sql'),
            reverse_sql='DROP TABLE IF EXISTS audit_log;'
        ),
        migrations.RunSQL(
            sql=load_sql_from_file('audit_authors_trigger.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS audit_authors_trigger;'
        ),
        migrations.RunSQL(
            sql=load_sql_from_file('audit_book_authors_trigger.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS audit_book_authors_trigger;'
        ),
        migrations.RunSQL(
            sql=load_sql_from_file('audit_books_trigger.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS audit_books_trigger;'
        ),
        migrations.RunSQL(
            sql=load_sql_from_file('audit_note_types_trigger.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS audit_note_types_trigger;'
        ),
        migrations.RunSQL(
            sql=load_sql_from_file('audit_notes_trigger.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS audit_notes_trigger;'
        ),
        migrations.RunSQL(
            sql=load_sql_from_file('audit_place_publishing_trigger.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS audit_place_publishing_trigger;'
        ),
        migrations.RunSQL(
            sql=load_sql_from_file('audit_user_books_trigger.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS audit_user_books_trigger;'
        ),
        migrations.RunSQL(
            sql=load_sql_from_file('audit_users_trigger.sql'),
            reverse_sql='DROP FUNCTION IF EXISTS audit_users_trigger;'
        )
    ]