# Generated by Django 5.2.9 on 2025-12-23 14:24

from django.db import migrations
import os

def load_sql_from_file(filename):
    sql_path = os.path.join(os.path.dirname(__file__), '..', 'sql', filename)
    with open(sql_path, 'r', encoding='utf-8') as f:
        return f.read()

class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_create_audit_table_with_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_from_file('audit_log_table.sql'),
            reverse_sql='DROP TABLE IF EXISTS audit_log;'
        )
    ]